name: Build

on:
  workflow_dispatch:
    inputs:
      ffmpegTag:
        description: 'FFmpeg Tag'
        required: true
        type: string
        
jobs:
  build:
    name: Build ffmpeg for windows
    runs-on: windows-latest

    steps:

      - name: setup toolchain
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      
      - name: checkout ffmpeg
        uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: ./ffmpeg
          ref: ${{ github.event.inputs.ffmpegTag }}

      - name: install nasm/yasm
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm nasm
          pacman -S --noconfirm yasm

      - name: make
        shell: msys2 {0}
        run: |
          cd ffmpeg
          ./configure --prefix=/d/ffmpeg_install \
          --enable-static 
          --disable-shared \
          --disable-debug
          --disable-gpl
          --disable-ffmpeg \
          --disable-ffprobe \
          --disable-ffplay \
          --disable-programs \
          --disable-symver \
          --disable-doc \
          --disable-htmlpages \
          --disable-manpages \
          --disable-podpages \
          --disable-txtpages \
          --disable-avresample \
          --disable-avfilter \
          --disable-avdevice \
          --disable-postproc \
          --disable-swscale \
          --disable-swresample
          -disable-everything
          make
          make install
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ffmpeg-install
          # Directory containing files to upload
          path: /ffmpeg_install
          
