name: Build

on:
  workflow_dispatch:
    inputs:
      ffmpegTag:
        description: 'FFmpeg Tag'
        required: true
        type: string
        
jobs:
  build:
    name: Build ffmpeg for windows
    runs-on: windows-latest

    steps:

      - name: setup toolchain
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            
      - name: checkout x264
        uses: actions/checkout@v3
        with:
            repository: mirror/x264
            path: ./x264
            ref: stable
      
      - name: checkout ffmpeg
        uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: ./ffmpeg
          ref: ${{ github.event.inputs.ffmpegTag }}

      - name: install nasm/yasm
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm nasm
          pacman -S --noconfirm yasm
      
      - name: make x264
        shell: msys2 {0}
        run: |
          cd x264
          ./configure --prefix=/d/x264_install \
          --enable-static
          make
          make install

      - name: make ffmpeg
        shell: msys2 {0}
        run: |
          cd ../ffmpeg
          ./configure --prefix=/d/ffmpeg_install \
          --extra-cflags=-l/d/x264_install/include  \
          --extra-ldflags=-L/d/x264_install/lib \
          --enable-static \
          --disable-shared \
          --disable-programs \
          --disable-doc \
          --disable-avdevice \
          --disable-swresample \
          --disable-swscale \
          --disable-postproc \
          --disable-avfilter \
          --disable-network \
          --enable-muxers \
          --enable-demuxers \
          --enable-encoders \
          --enable-protocols \
          --disable-random \
          --disable-zlib \
          --disable-bzlib \
          --disable-iconv
          make
          make install
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ffmpeg-install
          # Directory containing files to upload
          path: /ffmpeg_install
          
